name: kanaka_pg
services:
  # Main postgres database
  db:
    image: postgres:16
    container_name: kanaka_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: kanaka_db
      POSTGRES_PASSWORD: password
    ports:
      - "6543:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

volumes:
  kanaka_pg_data:
